language: python
services:
- docker
sudo: required
python:
- 3.5
- 3.8
env:
  global:
  - DOCKER_USERNAME=edxbuilder
  - secure: EHZhs9GVhl+b73ZdrOl75RKn3xIyw3DE3Dd18f/VlfG8XGMxLouojG8yF1JKgexxBPRiEYEfMbYUEw6duTqTHy11p8bo6TTp875bXm4p8KpQCXY406CfueabB5J/3UWhlTOmZCUUSuWRrtPdtbS0i1N296tnWFrlhFWuva5oeS0=
before_install:
- docker-compose -f .travis/docker-compose-travis.yml up -d
- docker exec xqueue bash -c "source /edx/app/xqueue/venvs/xqueue/bin/activate; cd
  /edx/app/xqueue/xqueue/; pip install -r requirements/travis.txt"
script:
- docker exec xqueue bash -c "source /edx/app/xqueue/venvs/xqueue/bin/activate; cd
  /edx/app/xqueue/xqueue/; TOXENV=${TOXENV} tox"
after_success:
- pip install -r requirements/travis.txt
- docker exec xqueue bash -c "source /edx/app/xqueue/venvs/xqueue/bin/activate; cd
  /edx/app/xqueue/xqueue/; coverage combine; coverage xml"
- codecov
branches:
  only:
  - master
deploy:
  provider: script
  script: make travis_docker_push
  on:
    branch: master
